### ISSUE TITLE
Add option to directly replace field with JSON-serialized value

### ISSUE THREAD

**Issue by marvin-roesch** [kazanzhy/kafka-connect-transform-record2row#1]
This SMT seems super helpful, I was surprised something like this didn't exist already. However, there is one issue I have with it right now that would require some workarounds to bring our data into a nice shape.

Before the field value is converted to JSON, you wrap it with a struct first, which would transform a field called "nested" with a value like the following
```json
{
  "obj": { "a": "foo", "b": "bar" },
  "arr": [1, 2, 3]
}
```
into the string value
```json
"{\"nested\":{\"obj\":{\"a\":\"foo\",\"b\":\"bar\"},\"arr\":[1,2,3]}}"
```
that gets written back to the `nested` field in the output record. When this data now gets inserted into e.g. a Postgres JSONB column, I'd have to query the `obj.a` value like this:
```sql
SELECT nested -> 'nested' -> 'obj' -> 'a' FROM table;
```
That seems like unnecessary duplication to me and is a little unergonomic for the user. It would be nicer if they could just write
```sql
SELECT nested -> 'obj' -> 'a' FROM table;
```
Thus, an option to skip the struct-nesting step of the transformation would be much appreciated. I might give implementing it myself a go if that's welcome.

**Comment by kazanzhy** [comment]
Hi @PaleoCrafter. Thank you for your feedback.

First, I want to say that a very similar SMT was released much earlier and inspired me to create this one. (See https://github.com/an0r0c/kafka-connect-transform-tojsonstring/).
You could try to use [record2jsonstring SMT](https://www.confluent.io/hub/an0r0c/kafka-connect-transform-record2jsonstring) and create a view in Postgres which will flatten this single JSON.

Talking about the additional field must say that it's a known issue. 
When I started to develop it I wanted to make it exactly how you described it. It's because my motivation was to use Kafka Connect as an extract and load tool from Mongo to Postgres and here's the [forum topic](https://forum.confluent.io/t/3291) about it.

But during the development, I've had to use some external libraries to convert `ConnectRecord` with many nested fields to another `ConnectRecord` where some fields were transformed to another data type. 
I used `AvroJsonSchemafulRecordConverter` from https://github.com/hpgrahsl/kafka-connect-mongodb. It can convert only `Struct` to `BsonDocument` which has `toString` method. Because only `Struct` has `fields()` method, see [the source code](https://github.com/hpgrahsl/kafka-connect-mongodb/blob/master/src/main/java/at/grahsl/kafka/connect/mongodb/converter/AvroJsonSchemafulRecordConverter.java#L93).

I see a few possible ways to resolve this problem.
1. Implement the own converter based on `AvroJsonSchemafulRecordConverter`. It also will significantly reduce the jar size. But you can see that there is a pretty huge bunch of code and it will take a lot of time.
2. Use some other converter. I didn't find such one but I'll look for it.

Nonetheless, I'm planning to improve this SMT, but it won't be soon. Also, it'll be great if you join to development. PRs are very welcomed.

**Comment by marvin-roesch** [comment]
Thanks for the prompt reply, @kazanzhy! That makes a lot of sense, I can see why you implemented this the way you did.

I think in the long term, your first option would be the for the best, and something I'd be more than happy to contribute (to). I would say a lot of the complexity of the Mongo converter stems from the idiosyncrasies of Mongo-consumable BSON documents, and one that goes straight from a Kafka Connect/Avro record to JSON could be much simplified.

I'll see about getting a draft of a custom converter done over the course of the next week. I think the big "challenge" is deciding how to serialize some of the types that do not map straight to JSON and whether the original schema should be recoverable from the converted JSON, something I think the BSON converter does.

In my case, dropping any type/schema information from the JSON would be sufficient, so all number types like `int8` or `float64` could just be mapped to regular JSON numbers etc. `bytes` fields are the only ones where I'm a bit conflicted. The converter could either apply a base64 or similar encoding or it could write the bytes as a string with escape sequences.

What are your thoughts on those two issues?
